Make ParserContext generic, with a Parser trait.
servo/rust-selectors pull request #101
Opened 2016-11-21 18:24 UTC by SimonSapin

r? @nox

2016-11-21 23:56 UTC, nox requested changes
Some questions and nits, r=me otherwise.

2016-11-21 23:56 UTC, nox commented on src/parser.rs
> +    /// aka Selector Group in http://www.w3.org/TR/css3-selectors/#grouping
https://drafts.csswg.org/selectors/#grouping would be better no?

2016-11-21 23:56 UTC, nox commented on src/parser.rs
> +            .expect("Empty SelectorList, should contain at least one selector");
What about returning `Err(fmt::Error)`?

2016-11-21 23:56 UTC, nox commented on src/parser.rs
> +            assert_eq!(selectors.0[0].to_css_string(), input);
Could you deref to the Vec instead?

2016-11-21 23:56 UTC, nox commented on src/parser.rs
> +    type Impl: SelectorImpl;
Could we merge it with `SelectorImpl`?

2016-11-21 23:56 UTC, nox commented on src/parser.rs
> +                                          name: Cow<str>,
What's the use for this?

2016-11-22 13:14 UTC, SimonSapin commented on src/parser.rs
> +    /// aka Selector Group in http://www.w3.org/TR/css3-selectors/#grouping
Done.

2016-11-22 13:14 UTC, SimonSapin commented on src/parser.rs
> +                                          name: Cow<str>,
In case this callback wants to take ownership of a `String` for the name.

2016-11-22 13:16 UTC, SimonSapin commented on src/parser.rs
> +            .expect("Empty SelectorList, should contain at least one selector");
I don’t think that would be appropriate, `fmt::Error` is for writing to the stream fails. And a selector list really should not be empty. (But that’s not worth enforcing with the type system.)

2016-11-22 13:17 UTC, SimonSapin commented on src/parser.rs
> +            assert_eq!(selectors.0[0].to_css_string(), input);
It could, but I don’t think it’s appropriate as it’s not a pointer.

2016-11-22 13:17 UTC, nox commented
@bors-servo r+

2016-11-22 13:17 UTC, bors-servo commented
:pushpin: Commit 8fcd5cb has been approved by `nox`

<!-- @bors-servo r=nox 8fcd5cbfe9e850210106631b014e5d80a036cf40 -->

2016-11-22 13:17 UTC, bors-servo commented
:hourglass: Testing commit 8fcd5cb with merge 90972b9...

2016-11-22 13:37 UTC, bors-servo commented
:sunny: Test successful - [status-travis](https://travis-ci.org/servo/rust-selectors/builds/177964451)

2016-11-22 13:37 UTC, merged